#!/bin/bash
set -euo pipefail

# Uninstall superpowerd — reverses everything setup.sh did.
#
# Usage:
#   bash uninstall.sh              # Remove superpowerd config (keep project dir)
#   bash uninstall.sh --purge      # Also delete the project directory

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
PURGE=false
[[ "${1:-}" == "--purge" ]] && PURGE=true

echo ""
echo "  superpowerd uninstall"
echo ""

# Stop and remove launchd services (macOS)
echo "==> Stopping services"
if [[ "$(uname)" == "Darwin" ]]; then
  for label in com.superpowerd.monitor com.superpowerd.dashboard; do
    PLIST="$HOME/Library/LaunchAgents/${label}.plist"
    if [[ -f "$PLIST" ]]; then
      launchctl bootout "gui/$(id -u)" "$PLIST" 2>/dev/null || \
        launchctl unload "$PLIST" 2>/dev/null || true
      rm -f "$PLIST"
      echo "    Removed $label"
    fi
  done
else
  # systemd (Linux)
  for service in superpowerd-monitor superpowerd-dashboard; do
    systemctl --user disable --now "$service" 2>/dev/null || true
    rm -f "$HOME/.config/systemd/user/${service}.service"
    echo "    Removed $service"
  done
  systemctl --user daemon-reload 2>/dev/null || true
fi

# Remove WezTerm config
echo "==> Removing WezTerm config"
if [[ -f "$HOME/.config/wezterm/wezterm.lua" ]]; then
  # Only remove if it's ours (check for superpowerd reference)
  if grep -q "superpowerd\|SUPERPOWERD" "$HOME/.config/wezterm/wezterm.lua" 2>/dev/null; then
    rm -f "$HOME/.config/wezterm/wezterm.lua"
    echo "    Removed wezterm.lua"
  else
    echo "    Skipped wezterm.lua (not ours)"
  fi
fi

# Remove pane title hook
echo "==> Removing shell hooks"
rm -f "$HOME/.config/iterm2/pane-title.zsh"

# Remove skhd config (only if auto-generated by superpowerd)
if [[ -f "$HOME/.config/skhd/skhdrc" ]]; then
  if grep -q "superpowerd\|Auto-generated" "$HOME/.config/skhd/skhdrc" 2>/dev/null; then
    rm -f "$HOME/.config/skhd/skhdrc"
    echo "    Removed skhdrc"
  fi
fi

# Remove Claude Code slash commands
echo "==> Removing Claude commands"
for cmd in "$PROJECT_DIR"/commands/*.md; do
  [[ -f "$cmd" ]] || continue
  LINK="$HOME/.claude/commands/$(basename "$cmd")"
  if [[ -L "$LINK" ]]; then
    rm -f "$LINK"
    echo "    Removed $(basename "$cmd")"
  fi
done

# Remove SessionStart hook from settings.json
echo "==> Removing auto-capture hook"
SETTINGS_FILE="$HOME/.claude/settings.json"
if [[ -f "$SETTINGS_FILE" ]]; then
  node -e "
    var fs = require('fs');
    var settings = JSON.parse(fs.readFileSync('$SETTINGS_FILE', 'utf8'));
    if (settings.hooks && settings.hooks.SessionStart) {
      settings.hooks.SessionStart = settings.hooks.SessionStart.filter(function(h) {
        return !(h.hooks && h.hooks.some(function(hh) { return hh.command && hh.command.includes('capture-hook'); }));
      });
      if (settings.hooks.SessionStart.length === 0) delete settings.hooks.SessionStart;
      fs.writeFileSync('$SETTINGS_FILE', JSON.stringify(settings, null, 2) + '\n');
      console.log('    Removed hook');
    }
  " 2>/dev/null || true
fi

# Remove superpowerd block from .zshrc
echo "==> Cleaning .zshrc"
ZSHRC="$HOME/.zshrc"
if [[ -f "$ZSHRC" ]] && grep -q "# superpowerd" "$ZSHRC"; then
  # Remove the superpowerd block (from "# superpowerd" to the next blank line or end)
  node -e "
    var fs = require('fs');
    var content = fs.readFileSync('$ZSHRC', 'utf8');
    var lines = content.split('\n');
    var result = [];
    var inBlock = false;
    for (var i = 0; i < lines.length; i++) {
      if (lines[i].trim() === '# superpowerd') {
        inBlock = true;
        continue;
      }
      if (inBlock) {
        // End block at next blank line or non-superpowerd content
        if (lines[i].trim() === '' && i + 1 < lines.length && !lines[i+1].includes('SUPERPOWERD') && !lines[i+1].includes('sp-') && !lines[i+1].includes('pane-title') && !lines[i+1].includes('CLAUDE_CODE_DISABLE')) {
          inBlock = false;
          continue;
        }
        if (lines[i].includes('SUPERPOWERD') || lines[i].includes('sp-rotate') || lines[i].includes('sp-monitor') || lines[i].includes('sp-dashboard') || lines[i].includes('pane-title') || lines[i].includes('CLAUDE_CODE_DISABLE_TERMINAL_TITLE')) {
          continue;
        }
        inBlock = false;
      }
      result.push(lines[i]);
    }
    fs.writeFileSync('$ZSHRC', result.join('\n'));
    console.log('    Removed superpowerd block');
  " 2>/dev/null || true
fi

# Remove hosts entry
if grep -q "superpowerd.local" /etc/hosts 2>/dev/null; then
  echo "==> Removing hosts entry (needs sudo)"
  sudo sed -i '' '/superpowerd.local/d' /etc/hosts 2>/dev/null || \
    echo "    Run: sudo sed -i '' '/superpowerd.local/d' /etc/hosts"
fi

# Purge project directory
if $PURGE; then
  echo "==> Removing project directory"
  rm -rf "$PROJECT_DIR"
  echo "    Deleted $PROJECT_DIR"
else
  echo ""
  echo "Project directory kept at: $PROJECT_DIR"
  echo "Run with --purge to delete it too."
fi

echo ""
echo "=== Uninstall complete ==="
echo ""
echo "Restart your shell or run: source ~/.zshrc"
